# Generated by Django 5.2.11 on 2026-02-21 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_dailymeal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_peanuts', models.BooleanField(default=False, verbose_name='Peanut Allergy')),
                ('allergy_dairy', models.BooleanField(default=False, verbose_name='Dairy Allergy')),
                ('allergy_gluten', models.BooleanField(default=False, verbose_name='Gluten Allergy')),
                ('allergy_seafood', models.BooleanField(default=False, verbose_name='Seafood Allergy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
