# Generated by Django 5.2.11 on 2026-02-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_add_userprofile_allergy_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allergy_dairy',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allergy_gluten',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allergy_peanuts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allergy_seafood',
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='e.g. peanut, milk, shrimp, wheat, egg', max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='tracker.userprofile')),
            ],
            options={
                'verbose_name': 'Allergy Keyword',
                'verbose_name_plural': 'Allergy Keywords',
                'ordering': ['keyword'],
                'unique_together': {('profile', 'keyword')},
            },
        ),
    ]
