# Generated by Django 5.2.11 on 2026-02-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_add_userallergy_keyword_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Resident height in centimetres', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_notes',
            field=models.TextField(blank=True, default='', help_text='Any additional medical or dietary notes for this resident'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Resident weight in kilograms', max_digits=5, null=True),
        ),
    ]
