# Generated by Django 5.2.11 on 2026-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
